clipper \SimaClip.v52\SimaMatr\f\funcions\MatriFun /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsAdm /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsEmp /w/m/b

clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsCon /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsTar /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsBan /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsPag /w/m/b

clipper \SimaClip.v52\SimaMatr\f\funcions\ContaFun /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsAlu /w/m/b
clipper \SimaClip.v52\SimaMatr\f\funcions\FuncsNiv /w/m/b




copy *.obj \SimaClip.v52\SimaMatr\f\objs
del  *.obj
del \SimaClip.v52\SimaMatr\f\funcions\*.bak
