	 MODIFICACIONES PENDIENTES PARA EL SISTEMA DE CARTERA

NOV /97

- Fecha de Entrega: Nov 10/97
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Recibos Nuevos
  Colegios........: Tecnologico, La Merced.

- Fecha de Entrega: Nov 20/97
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Paz y Salvos.
  Colegios........: La Salle, La Merced


FEB /98

- Fecha de Entrega: Feb 01/98
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Manejo de Rutas
  Colegios........: San Bernardo.

- Fecha de Entrega: Feb 10/98
  Fecha de Inicio :                    Fecha Final:
  Programa para   : Adecuaci¢n Gerencia Electronica
  Colegios........: La Merced

