copy \simaclip.v52\clipper.fun\f\epsonfx.prg  \simaclip.v52\clipper.fun
copy \simaclip.v52\clipper.fun\f\epsonfx1.prg \simaclip.v52\clipper.fun

clipper \simaclip.v52\clipper.fun\f\funcsdbf /w/m/b
clipper \simaclip.v52\clipper.fun\f\funcsnel /w/m/b
clipper \simaclip.v52\clipper.fun\f\archinel /w/m/b
clipper \simaclip.v52\clipper.fun\f\classnel /w/m/b
clipper \simaclip.v52\clipper.fun\f\funcsprn /w/m/b
rem clipper \simaclip.v52\clipper.fun\f\funcsusr /w/m/b
clipper \simaclip.v52\clipper.fun\f\usrcrypt /w/m/b
clipper \simaclip.v52\clipper.fun\f\fwwwusr
clipper \simaclip.v52\clipper.fun\f\fTipoUsr /w/m/b
clipper \simaclip.v52\clipper.fun\f\funcserr /w/m/b
clipper \simaclip.v52\clipper.fun\f\OtrErr01 /w/m/b
clipper \simaclip.v52\clipper.fun\f\FuncsAyu /w/m/b
clipper \simaclip.v52\clipper.fun\f\FunColor /w/m/b
clipper \simaclip.v52\clipper.fun\f\printer /w/m/b
clipper \simaclip.v52\clipper.fun\f\FuncsXml /w/m/b
clipper \simaclip.v52\clipper.fun\f\FuncsCsv /w/m/b
clipper \simaclip.v52\clipper.fun\f\FileSys /w/m/b
clipper \simaclip.v52\clipper.fun\f\FileStr /w/m/b
clipper \simaclip.v52\clipper.fun\f\FilePrg /w/m/b
clipper \simaclip.v52\clipper.fun\f\FuncsStr /w/m/b
clipper \simaclip.v52\clipper.fun\f\printIso /w/m/b

clipper \simaclip.v52\clipper.fun\f\gFuncPer /w/m/b

clipper \simaclip.v52\clipper.fun\f\eFuncPer /w/m/b

copy *.obj \simaclip.v52\clipper.fun
del  *.obj
del  *.bak
del  \simaclip.v52\clipper.fun\*.bak
