/*                   SISTEMA DE CONTABILIDAD ACADEMICA
		   REGISTRO DE MODIFICACIONES PENDIENTES

*------------------------------------------------------------------------*
*                  PROCESOS PENDIENTES DE PROGRAMANCION                  *
*------------------------------------------------------------------------*/

Codigo No. 2002ENE-1
Fecha y Hora..: => Inicio:         Final:         Versi¢n:
Titulo........: Facturaci¢n de Recibos.
Tipo..........: Modificaci¢n sustancial

Descripci¢n:
- Permitir facturar uno o varios conceptos en diferentes recibos.
- Unificar un solo Estado de Cuenta.
- Conciliar cada uno de los Recibos seg£n extractos.
*========================================================================*

Codigo No. 2002ENE-2
Fecha y Hora..: => Inicio:         Final:         Versi¢n:
Titulo........: Extracto seg£n Contabilidad
Tipo..........: Mejora al Sistema.

Descripci¢n:
- Descriminar cada uno de los conceptos del extracto seg£n las cuentas
  de contabilidad.
*========================================================================*

Codigo No. 2002ENE-3
Fecha y Hora..: => Inicio:         Final:         Versi¢n:
Titulo........: Informe de Morosos
Tipo..........: Error en Sistema

Descripci¢n:
- Al imprimir el informe de morosos con corte de fecha genera error.
*========================================================================*

