/*                       SIMA - SISTEMA DE CAFETERIA
		     DETALLES DE INSTALACION DE EMPRESAS

**************************************************************************
* TITULO..: DETALLES DE INSTALACION                                      *
**************************************************************************

AUTOR: Nelson Fern ndez G¢mez       FECHA DE CREACION: MAY 20/2002 LUN A
       Colombia, Bucaramanga        INICIO: 01:10 PM   MAY 20/2002 LUN

OBJETIVOS:

1- Declara todas las variables que contiene los detalles de instalaci¢n
   de cada una de las empresas a las cuales se le ha instalado el sistema.

2- El objetivo principal es controlar los detalles de instalaci¢n de
   cada empresa.

*------------------------------------------------------------------------*
*                              PROGRAMA                                  *
*------------------------------------------------------------------------*/

*>>>>DECLARACION DE EMPRESAS INSTALADAS
/*
*      FECHA DE INSTALACION: SEP 28/2000 HORA: 10:00 AM
*      RECIBO Y VISTO BUENO: ALEJO.
*                                                                |         |
       LOCAL cEmpPal := 'COLEGIO DE PRUEBA XYZ'
       LOCAL cNitEmp := '860009985-0'
       LOCAL cNomEmp := 'COLEGIO DE PRUEBA XYZ'
       LOCAL cNomSec := ''                  // Nombre Secundario
       LOCAL cMaeAlu := 'JARPRIBTO'         // Maestros habilitados
       LOCAL cJornad := 'DNMT'              // Jornadas habilitadas
       LOCAL lShared := .T.                 // .T. Sistema Compartido
       LOCAL nModCry := 0                   // 0=>No Protecci¢n 1=>Sin Proteci¢n Inicial 2=>Con Proteci¢n Inicial
       LOCAL lNovell := .T.                 // .T. Red Novell .F. Red Win NT
       LOCAL cPasSis := 'ELLAS'             // PassWord Creaci¢n usuarios
       LOCAL lPrueba := .T.                 // Prueba de Paramentros
       LOCAL aKeySis := {{83951702,23},;    // 151146918
			 {cNomEmp,487023780},;
			 {cMaeAlu,151152049},;
			 {'System',419845542}}
*/

/*
*      FECHA DE ENTREGA    : JUL 04/2001 HORA: 04:30 PM
*      RECIBO Y VISTO BUENO: ING NESTOR ALEJANDRO PINZON. SISTEMAS

       LOCAL cEmpPal := 'COLEGIO ABC'
       LOCAL cNitEmp := '999999999-9'
       LOCAL cNomEmp := 'COLEGIO ABC'
       LOCAL cNomSec := ''                  // Nombre Secundario
       LOCAL cMaeAlu := 'PRIBTO'            // Maestros habilitados OJO JAR
       LOCAL cJornad := 'D'                 // Jornadas habilitadas
       LOCAL lShared := .F.                 // .T. Sistema Compartido
       LOCAL nModCry := 0                   // 0=>No Protecci¢n 1=>Con Proteci¢n Inicial 2=>Sin Proteci¢n Inicial
       LOCAL lNovell := .F.                 // .T. Red Novell .F. Red Win NT
       LOCAL cPasSis := 'ELLAS'             // PassWord Creaci¢n usuarios
       LOCAL lPrueba := .F.                 // Prueba de Paramentros
       LOCAL aKeySis := {{201553870,23},;   // Pendientes las claves
			 {cNomEmp,554226449},;
			 {cMaeAlu,151152049},;
			 {'System',419845542}}
*/

/*
*      FECHA DE INSTALACION: FEB 22/96 HORA: 10:00 AM
*      RECIBO Y VISTO BUENO: ZORAIDA. PAGADORA
*                       '123456789012345678901234567890123456789012'
       LOCAL cEmpPal := 'CONGREGACION DE LOS HNOS DE LAS ESCUELAS CRISTIANAS'
       LOCAL cNitEmp := '860009985-0'
       LOCAL cNomEmp := 'COLEGIO LA SALLE. BUCARAMANGA'
       LOCAL cNomSec := ''                  // Nombre Secundario
       LOCAL cCodCol := 'CSAN0011'          // C¢digo del Colegio
       LOCAL cMaeAlu := 'PRIBTO'            // Maestros habilitados
       LOCAL cJornad := 'D'                 // Jornadas habilitadas
       LOCAL lShared := .T.                 // .T. Sistema Compartido
       LOCAL nModCry := 0                   // 0=>No Protecci¢n 1=>Sin Proteci¢n Inicial 2=>Con Proteci¢n Inicial
       LOCAL lNovell := .T.                 // .T. Red Novell .F. Red Win NT
       LOCAL cPasSis := 'ELLAS'             // PassWord Creaci¢n usuarios
       LOCAL lPrueba := .F.                 // Prueba de Paramentros
       LOCAL aKeySis := {{83951702,23},;    // 151146918
			 {cNomEmp,487023780},;
			 {cMaeAlu,151152049},;
			 {'System',419845542}}
*/


*      FECHA DE INSTALACION: FEB 24/2000 HORA: 08:00 AM
*      RECIBO Y VISTO BUENO: VLADIMIR. SISTEMAS
*                       '123456789012345678901234567890123456789012'
       LOCAL cEmpPal := 'CONGREGACION DE LOS HNOS DE LAS ESCUELAS CRISTIANAS'
       LOCAL cNitEmp := '860009985-0'
       LOCAL cNomEmp := 'COLEGIO DE LA SALLE BOGOTA'
       LOCAL cCodCol := 'CCUN0011'          // C¢digo del Colegio
       LOCAL cNomSec := ''                  // Nombre Secundario
       LOCAL cMaeAlu := 'PRIBTO'            // Maestros habilitados
       LOCAL cJornad := 'D'                 // Jornadas habilitadas
       LOCAL lShared := .T.                 // .T. Sistema Compartido
       LOCAL nModCry := 0                   // 0=>No Protecci¢n 1=>Con Proteci¢n Inicial 2=>Sin Proteci¢n Inicial
       LOCAL lNovell := .F.                 // .T. Red Novell .F. Red Win NT
       LOCAL cPasSis := 'ELLAS'             // PassWord Creaci¢n usuarios
       LOCAL lPrueba := .F.                 // Prueba de Paramentros
       LOCAL aKeySis := {{201553870,23},;   // Pendientes las claves
			 {cNomEmp,554226449},;
			 {cMaeAlu,151152049},;
			 {'System',419845542}}
*>>>>FIN DECLARACION DE EMPRESAS INSTALADAS